version = 3.10.7
runner.dialect = scala3
align {
  tokens."+" = [
    "%",
    "%%",
    "<-",
    {code = "=", owner = "Param"},
    {code = "=>", owner = "Case"}
  ]
}
danglingParentheses.preset = true
docstrings.style = Asterisk
indentOperator.preset = spray
maxColumn = 110
newlines {
  afterInfix = keep
}
project {
  git = true
  excludeFilters = ["target"]
}
rewrite {
  rules = [PreferCurlyFors, RedundantBraces]
  redundantBraces.maxLines = 1
}
newlines.implicitParamListModifierPrefer = before