version: '3'

services:
  postgres:
    image: postgres:16.3
    environment:
      POSTGRES_DB: "${DATABASE_NAME}"
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
    ports:
      - "${DATABASE_PORT:-5432}:5432"
