service-name = "template-app"
server-port  = 8080

db {
  host = ${DATABASE_HOST}
  port = ${DATABASE_PORT}
  username = ${DATABASE_USER}
  password = ${DATABASE_PASSWORD}
  database = ${DATABASE_NAME}
  num-threads = ${DATABASE_THREADS_NUM}
}
